module.exports = {
  extends: ['.eslintrc.js'],
  parserOptions: {
    // disable rules that depend on type information - these would slow down git committing too much, rather rely on PR branch builds for these
    project: null,
  },
  rules: {
    'no-console': ['error', { allow: ['warn', 'error', 'info', 'time', 'timeEnd'] }],
    'no-debugger': 'error',
    '@typescript-eslint/*': 'off',
    '@typescript-eslint/prefer-nullish-coalescing': 'off',
    '@typescript-eslint/no-implied-eval': 'off',
    '@typescript-eslint/no-throw-literal': 'off',
    '@typescript-eslint/dot-notation': 'off',
    '@typescript-eslint/no-unsafe-return': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/no-unsafe-member-access': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/no-floating-promises': 'off',
    '@typescript-eslint/restrict-template-expressions': 'off',
    '@typescript-eslint/no-misused-promises': 'off',
    '@typescript-eslint/restrict-plus-operands': 'off',
    '@typescript-eslint/unbound-method': 'off',
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-namespace': 'off',
    'graphql/template-strings': 'off',
    'import/no-extraneous-dependencies': 'off',
  },
}
