name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.19.0 ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install -g yarn
          yarn install --prefer-offline --frozen-lockfile
          yarn build
